### ISSUE TITLE
V2 is missing at GitHub Action Marketplace

### ISSUE THREAD

**Issue by ep4sh** [nzbr/vlang-action#1]
Hi @nzbr,

thank you for developing vlang-action, it's very handy!

Could you please publish the `v2` of this action to the GH Actions Marketplace ([it looks like `v1` which is available in Marketplace is failing when v compile itself.](https://github.com/nzbr/vlang-action/commit/095870c59cf8ceb1e365afbf8bf0ef3349b429da) )

**Comment by nzbr** [comment]
Hi,

there was a v2 tag already, but apparently I had to create a release in order for it to show up on the marketplace. V2 is now listed as the latest version. Feel free to re-open this issue (or to create a new one) should there be a problem with it
